global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mealmonitor-monitor'

scrape_configs:
  # Eureka Server (Docker)
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']
        labels:
          application: 'MealMonitor-EurekaServer'

  # API Gateway (Docker)
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'MealMonitor-Gateway'

  # User Service (Running Locally)
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']
        labels:
          application: 'MealMonitor-UserService'

  # Canteen Service (Running Locally on port 8086, NOT running currently)
  - job_name: 'canteen-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8086']
        labels:
          application: 'MealMonitor-CanteenService'

  # Review Service (Running Locally)
  - job_name: 'review-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']
        labels:
          application: 'MealMonitor-ReviewService'

  # Notification Service (Running Locally)
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8089']
        labels:
          application: 'MealMonitor-NotificationService'

  # Poll Service (Running Locally)
  - job_name: 'poll-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8087']
        labels:
          application: 'MealMonitor-PollService'

  # Moderation Service (Running Locally)
  - job_name: 'moderation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8088']
        labels:
          application: 'MealMonitor-ModerationService'

  # Web App (Running Locally)
  - job_name: 'web-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8085']
        labels:
          application: 'MealMonitor-WebApp'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'Prometheus'

