apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  type: NodePort
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
      nodePort: 31600
  selector:
    io.kompose.service: eureka-server
