server:
  port: 8085

spring:
  application:
    name: MealMonitor-WebApp
  web:
    resources:
      static-locations: classpath:/static/

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
